import auth
import main

auth_code = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJZWE5TVENVTFBLIiwidXVpZCI6IjhhNDExZGI1ODU3MjQxYzNiOWJjMWZhNjYwMmZiMjIxIiwiaXBBZGRyIjoiIiwibm9uY2UiOiIiLCJzY29wZSI6IiIsImRpc3BsYXlfbmFtZSI6IlhQMjQxMTEiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI3MmJhYjhiNGIyN2MxNjFhMWNjMjM3NDQ1NjNiNGYxN2NjZmVmNDAwYTQzNjczZjM1MDAxZWRhNSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImF1ZCI6IltcImQ6MVwiLFwiZDoyXCIsXCJ4OjBcIixcIng6MVwiLFwieDoyXCJdIiwiZXhwIjoxNzcwMjA2MTQzLCJpYXQiOjE3NzAxNzYxNDMsImlzcyI6ImFwaS5sb2dpbi5meWVycy5pbiIsIm5iZiI6MTc3MDE3NjE0Mywic3ViIjoiYXV0aF9jb2RlIn0.ukU9aWOTq9YnucLeFBZXVCOdqzgcGOU9M4ozrF2qL-Q"

try:
    print("Generating access token...")
    access_token = auth.generate_access_token(auth_code)
    main.save_access_token(access_token)
    print("Access token saved successfully.")
except Exception as e:
    print(f"Error generating token: {e}")
